"""create fauna lookup table

Revision ID: 52d96c9b568f
Revises: a2df25307aed
Create Date: 2024-03-23 16:17:55.149724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '52d96c9b568f'
down_revision: Union[str, None] = 'a2df25307aed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fauna',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('image_label', sa.Integer(), nullable=True),
    sa.Column('common_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('scientific_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('family', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fauna_class', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fauna_infra_class', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('conservation_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('habitat', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('diet', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('lifespan', sa.Integer(), nullable=True),
    sa.Column('geographic_range', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fun_fact', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fauna')
    # ### end Alembic commands ###
